POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Kelvin Nguyen",
    "number": "5042598189"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Kelvin Nguyen"
}